### ISSUE TITLE
Support for TYPO3 v10

### ISSUE THREAD

**Issue by Chrisswald** [b13/t3ext-geocoding#11]
Do you plan an update of your extension in the near future?

**Comment by bmack** [comment]
I updated the master branch, if you could test that with TYPO3 v10, I would gladly release a new version of EXT:geocoding

**Comment by Chrisswald** [comment]
Unfortunately it will take me a while until i will have updated the extension which is using geocoding. So far, i only were able to test it in v10 via the extension compatibility tools and it all seems cool.

I will give you an update...

**Comment by mbrodala** [comment]
@Chrisswald Where you able to check the latest state already?

**Comment by Chrisswald** [comment]
Unfortunately not. I think it will take some time until we will get started with the related project.

**Comment by Chrisswald** [comment]
@mbrodala I tested it and it works.

**Comment by bmack** [comment]
@Chrisswald so this works without any adaptions? I will put it on my list to release in the next few days.

**Comment by Chrisswald** [comment]
Yes.

**Comment by bmack** [comment]
Just released EXT:geocoding 4.2.0
