### ISSUE TITLE
Check for empty `$addressPart` can fail

### ISSUE THREAD

**Issue by rintisch** [b13/t3ext-geocoding#15]
Is neither city nor zip is entered the check `if (empty($addressPart))` fails because a white space makes `$addressPart` being not empty.

 https://github.com/b13/geocoding/blob/f8cfd7f9ba6197a6ec3b638c376d9cd430e6ca6e/Classes/Service/GeoService.php#L81-L88

Would be a solution to check with `strlen(trim($addressPart)) <= 0` instead.

Background: 
Otherwise this can lead to two consecutive commas. As a result the request leads sometimes to ` ZERO_RESULTS`.

Is the solution okay? Shall I make a PR?

**Comment by bmack** [comment]
Yes. Please go ahead.
