### ISSUE TITLE
typing error in GeoService.php

### ISSUE THREAD

**Issue by realJustmike** [b13/t3ext-geocoding#2]
GeoService.php, near line 230:
$cacheManager = GeneralUtility::makeInstance('TYPO3\CMS\Core\Cache\CacheMana**n**ger');

should be:
$cacheManager = GeneralUtility::makeInstance('TYPO3\CMS\Core\Cache\CacheManager');

**Comment by d4s6** [comment]
Fixed with commit b3c511029f127596ce242fbc891c75e7c435bab4.
