### ISSUE TITLE
API Key usage is not working

### ISSUE THREAD

**Issue by LimeUwe** [b13/t3ext-geocoding#4]
Hi,

even if a api key is configured in the extension settings, it won't be used, because it is commented out:

https://github.com/b13/t3ext-geocoding/blob/1b61fdd7e912b4378a8a1fabcb4fa4e1f5b5c86f/Classes/Service/GeoService.php#L60

Regards,
Uwe Michelfelder

**Comment by Schweriner** [comment]
I've added a pull request for this: https://github.com/b13/t3ext-geocoding/pull/6

**Comment by ervaude** [comment]
Done via #7
