### ISSUE TITLE
Geocoding API needs to be called with https

### ISSUE THREAD

**Issue by LimeUwe** [b13/t3ext-geocoding#5]
When using the Geocoding API with a key, the service needs to be called via https:

https://github.com/b13/t3ext-geocoding/blob/1b61fdd7e912b4378a8a1fabcb4fa4e1f5b5c86f/Classes/Service/GeoService.php#L43

Regards,
Uwe Michelfelder

**Comment by Schweriner** [comment]
I've added a pull request for this: https://github.com/b13/t3ext-geocoding/pull/6

**Comment by ervaude** [comment]
Done via #7
